//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id_Product { get; set; }
        public Nullable<int> id_Category { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string content { get; set; }
        public string img { get; set; }
        public Nullable<bool> hotproduct { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> brand_id { get; set; }
    }
}
