//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdSale
    {
        public int id_prodSale { get; set; }
        public string name { get; set; }
        public Nullable<int> newprice { get; set; }
        public Nullable<int> oldprice { get; set; }
        public Nullable<bool> Random { get; set; }
        public Nullable<bool> Bestseller { get; set; }
        public string img { get; set; }
        public Nullable<int> brand_id { get; set; }
        public Nullable<int> id_Category { get; set; }
        public Nullable<bool> HotSale { get; set; }
        public Nullable<bool> HotDeals { get; set; }
    }
}
